from typing import Protocol
from app.api.domain.entities import Server, ServerAlert, ServerMetrics
from app.api.domain.enums import ServerStatus


class ServerRepository(Protocol):
    def find_by_id(self, server_id: int) -> Server | None: ...
    def find_by_name(self, name: str) -> Server | None: ...
    def find_by_ip(self, ip: str) -> Server | None: ...
    def search(self, query: str) -> list[Server]: ...
    def find_all(self) -> list[Server]: ...
    def save(self, server: Server) -> Server: ...
    def update_status(self, server_id: int, status: ServerStatus) -> bool: ...
    def delete(self, server_id: int) -> bool: ...


class MetricsRepository(Protocol):
    def save(self, metrics: ServerMetrics) -> ServerMetrics: ...
    def find_latest(self, server_id: int) -> ServerMetrics | None: ...
    def find_history(self, server_id: int, limit: int = 10) -> list[ServerMetrics]: ...


class AlertRepository(Protocol):
    def save(self, alert: ServerAlert) -> ServerAlert: ...
    def find_active(self) -> list[ServerAlert]: ...
    def resolve(self, alert_id: int) -> bool: ...
